##################################################
### Install basic system packages
- name: "Install basic packages"
  ansible.builtin.apt: 
    name:
      - vim
      - git
      - curl
      - wget
      - zip
      - unzip
      - htop
      - iotop
      - debian-goodies
      - apt-transport-https
      - ca-certificates
      - imagemagick
    state: present

##################################################
### Convenience
- name: Configure inputrc and vimrc for root
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
   - { src: "inputrc", dest: "/root/.inputrc" }
   - { src: "vimrc", dest: "/root/.vimrc" }
   - { src: "inputrc", dest: "/home/vagrant/.inputrc" }
   - { src: "vimrc", dest: "/home/vagrant/.vimrc" }

##################################################
### Install and configure ufw firewall
- name: Set up firewall
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Allow Port 22
  community.general.ufw:
    port: "22"
    rule: allow

- name: Start the firewall
  community.general.ufw:
    state: enabled
