##################################################
### Install check_mk agent
- name: Install required packages
  apt:
    name: xinetd
    state: present

- name: Download check_mk agent
  get_url:
    url: "{{ checkmk_agent_url }}"
    dest: "/tmp/check_mk_agent.deb"

- name: Install check_mk agent
  shell: gdebi -n /tmp/check_mk_agent.deb
  become: yes

- name: Allow Port 6556
  ufw: rule=allow port=6556
